### ISSUE TITLE
Selettori volontari e loro permessi

### ISSUE THREAD

**Issue by ico88** [CroceRossaCatania/gaia#1441]
Questa issue ha lo scopo di chiarire una volta per tutte come dovrebbero funzionare i selettori su gaia per i singoli casi:

### Trasferimenti, estensioni e riserve 

Presidente e Ufficio soci possono trasferire, estendere o mettere in riserva i volontari appartenenti al loro comitato secondo il proprio livello:
- [x] Locale: può trasferire ed estendere tutti i volontari appartenenti al locale e alle unità sottostanti;
- [x] ~~Provinciale/Regionale/Nazionale: non possono ne trasferire ne estendere;~~ forse va affrontato dal punto di vista dei permessi della pagina?

### Deleghe 

Il presidente può nominare i delegati degli obiettivi e delle varie APP presenti su gaia secondo tale schema:
- [ ] Unità territoriale: i volontari appartenenti a essa o gli eventuali estesi verso tale unità;
- [ ] Locale: Tutti i volontari del locale e quindi anche delle unità territoriali ad esso afferenti, compresi estesi;
- [ ] Provinciale: Tutti i volontari del provinciale e dei comitati locali a lui afferenti, quindi anche delle unità territoriali, compresi estesi;
- [ ] Regionale: Tutti i volontari del regionale, dei comitati provinciali e dei comitati locali a lui afferenti, quindi anche delle unità territoriali, compresi estesi;
- [ ] Nazionale: Qualunque volontario in italia, compresi estesi;

Riassumiamo qui le altre issue: 
- [ ] Ref #1282 Nominare come delegati volontari in estensione;
- [ ] Ref #1428 [autoparco] delegare funzione operativa anche ai volontari estesi;

### Attività 
Il selettore attività deve lavorare su mio livello delega e su estensione attività, il livello massimo di apertura sarà sempre pari al mio livello delega, esempi:
- [x] se sono presidente locale e l'attività è nazionale potrò aggiungere solo volontari o estesi del mio comitato locale;
- [x] se l'attività è locale e io sono presidente nazionale potrò aggiungere solo volontari o estesi massimo del locale in cui si svolge l'attività.
I volontari sono frutto quindi dell'intersezione dell'insieme dei volontari possibili per livello delega e dell'insieme dei volontari possibili per estensione attività.

Ciò permetterà al presidente ad una attività di tipo regionale di aggiungere i propri volontari, fatto salvo comunque il discorso delle autorizzazioni.

Riassumiamo qui le altre issue argomento correlate: 
- [ ] Ref #1320 Permettere al Presidente di inserire volontari in attività non sue;
- [ ] Ref #1366 Attività: il referente non può selezionare volontari in estensione;
- [x] Ref #1335 Problema selettore volontari;

- [ ] Sarebbe carino che gli admin potessero in qualunque selettore avere comunque tutti i volontari d'Italia.
