### ISSUE TITLE
Migliorare gestione accettazione preiscrizioni

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaCatania/gaia#1522]
Introdurre queste cose:
- [x] far accettare le preiscrizioni solamente dopo l'inizio del corso base
- [x] informare chi accetta la preiscrizione che la persona diventa socio ordinario CRI
- [x] obblicare chi accetta la preiscrizioni a indicare che sono in ordine i documenti cartacei di iscrizione, in particolare l'autocertificazione per carichi pendenti, la firma del codice di condotta e tutto ciò che è previsto dal regolamento
