### ISSUE TITLE
email mancanti nei corsi base

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaCatania/gaia#1534]
Non sono state implementate una serie di email:
- [x] preiscrizione non accettata (da direttore a preiscritto)
- [x] ordinario iscritto a corso base (da direttore a ordinario, da sistema a direttore)
- [x] direttore selezionato (da presidente a direttore)
