### ISSUE TITLE
[amazon] Progettare un sistema di deployment automatico su AWS EB

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaCatania/gaia#1634]
Al fine di portare Gaia sul sistema AWS ElasticBeanstalk, che rendera' l'infrastruttura capace di scalare automaticamente, e' necessario prevedere un sistema adeguato di deployment automatico, in grado di ricreare l'infrastruttura e impostare correttamente un app server, anche in previsione della scalabilita' orizzontale.
- [ ] Modifiche necessarie a rendere Gaia scalabile orizzontalmnente su piu' App Server;
- [ ] Procedura di deployment automatico App Server (Docker o EB PHP);
- [ ] Provisioning delle configurazioni con meccanismi compatibili con AWS;
- [ ] Provisioning automatico di MySQL (RDS), Redis (ElastiCache) e MongoDB (EC2);
- [ ] Raccolta automatica dei log
- [ ] Esecuzione task (cronjob, mailer)
