### ISSUE TITLE
[db] errori vari in apertura pagine

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1975]
- [x] quanto 9934 genera elenco soci regionale in formato zip (admin.utenti.excel) ottiene:
5517b0a09b7fd2d066f034cd string(50) "Call to a member function format() on a non-object"
- [x] quando 32807 modifica attività ottiene:
55143e959b7fd2804ec0f971 
- [x] quando 40383 apre la pagine del corso base (di cui è direttore) ottiene:
5506f5669b7fd2e808fe7670
- [x] quando 62179 apre un'attività ottiene:
5523e9869b7fd2773af099cd string(98) "Uncaught 20150407162822 [ERR #1003]: Entità non presente (tabella:id) => 	comitati:3266
- [x] quando 3074 apre l'attività ottiene 55267d6a9b7fd2cb5c530aec string(109) "Uncaught 20150409152354 [ERR #1000]: Errore non documentato - fare riferimento al supporto tecnico
- [x] quando 55661 apre turni di varie attività ottiene errore.
- [x] quando 1572 apre le attività esse non si caricano
- [x] quando 10226 genera elenco volontari ZIP ottiene 552fbf9f9b7fd2fa3e7c8050 "Call to a member function format() on a non-object"
- [x] quando 11368 apre i servizi trova 552f54709b7fd2895d538669 "Uncaught [ERR #1011]: Almeno un parametro richiesto non e' stato specificato
- [x] quando 62179 apre i servizi riceve 5537694b9b7fd2cb69fe14d9 "Uncaught [ERR #1011]: Almeno un parametro richiesto non e' stato specificato
- [x] quando 12293 apre i servizi riceve 5534b7d89b7fd22a3be05534 "Uncaught [ERR #1011]: Almeno un parametro richiesto non e' stato specificato
- [x] quando 12569 genera elenco soci riceve 55313cd69b7fd22c77c6b711 
- [x] quando 2054 genera elenco soci riceve 55313cd69b7fd22c77c6b711 
- [x] quando 11368 apre ?p=attivita.autorizzazioni ottiene errore fatale "Almeno un parametro richiesto non e' stato specificato"
- [x] quando 109893 apre ?p=attivita.scheda&id=6200 ottiene 5548ce439b7fd2fc4a3b9509 "Entità non presente (tabella:id) => 	attivita:61200"
- [x] quando il presidente 13119 genera l'elenco soci excel ottiene 5548b0bc9b7fd28167457d2c
- [x] quando 37450 apre la pagina delle attività chiuse riceve 555071729b7fd2360bf5b6c7 Entità non presente (tabella:id) => 	aree:4726
- [x] quando 20009 cerca di inserire un'attività riceve 55571c269b7fd2692e7c9a16 "Call to a member function getTimestamp() on a non-object"
- [x] quando 213 prova a autorizzare un servizio ad un socio riceve 555a045a9b7fd23821af0e9a
- [x] quando 14 apre la pagina delle autorizzazioni alle attività trova 554cef1b9b7fd2b67ac891e4
- [x] quando 3635 apre la pagina di dettaglio dell'unità territoriale "Niscemi" riceve errore fatale.
- [x] quando 4528 apre la rubrica ottiene 5561e1949b7fd2ff7659725f "Uncaught 20150524163500 [ERR 1011]: Almeno un parametro richiesto non e' stato specificato thrown"
- [x] quando 3966 apre la rubrica ottiene "Uncaught 20150524163500 [ERR 1011]: Almeno un parametro richiesto non e' stato specificato thrown"

**Comment by matthewmazzoleni** [comment]
aumentano segnalazioni

**Comment by matthewmazzoleni** [comment]
aumentano segnalazioni

**Comment by AlfioEmanueleFresta** [comment]
Queste partecipazioni con volontari non esistenti son andate via
![image](https://cloud.githubusercontent.com/assets/621062/7379592/dc638e60-eded-11e4-9e26-0e8b59476baa.png)

**Comment by ico88** [comment]
Pian piano che risolvo spunto

**Comment by ico88** [comment]
@matthewmazzoleni non riesco a replicare: "quando 32807 modifica attività ottiene: 55143e959b7fd2804ec0f971"

**Comment by ico88** [comment]
@matthewmazzoleni cosa intendi per apre i servizi ?

**Comment by AlfioEmanueleFresta** [comment]
@ico88 quelli che non riesci a replicare devo averli risolti ieri con quelle query `sarbagge`

**Comment by ico88** [comment]
@AlfioEmanueleFresta chiudiamo e al max riapriamo ?

**Comment by AlfioEmanueleFresta** [comment]
Con la collaborazione di @matthewmazzoleni, approvo

**Comment by ico88** [comment]
Perchè chiudi ? non tutti sono non replicabili

**Comment by matthewmazzoleni** [comment]
@ico88 apre la pagina dei servizi (come referente) o i turni (come partecipante)

**Comment by ico88** [comment]
Per servizi intendi le attività giusto ?

**Comment by matthewmazzoleni** [comment]
si @ico88

**Comment by matthewmazzoleni** [comment]
aumentano segnalazioni

**Comment by PaoloGiustiniani** [comment]
E' abbastanza urgente.

**Comment by PaoloGiustiniani** [comment]
Sollecito.

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani e @matthewmazzoleni, vi prego di continuare a inviare errori. Sfortunatamente fino a Jorvik questi errori vanno risolti uno ad uno (ad ogni risoluzione puo' seguire un fix del problema di fondo), ma c'e' necessita dei codici errore (che durano una settimana).

**Comment by ico88** [comment]
Molta roba è chiusa già
